FROM alpine:3.15.0
ENV TZ=Asia/Shanghai
ENV LANG=zh_CN.UTF-8
ENV LC_ALL=zh_CN.utf8
WORKDIR /
EXPOSE 8080

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.cloud.tencent.com/g' /etc/apk/repositories \
    && apk add --no-cache gcompat tzdata ca-certificates curl \
    && rm -rf /var/cache/apk/*
RUN cp /usr/share/zoneinfo/${TZ} /etc/localtime && echo "${TZ}" >  /etc/timezone

ADD {{.buildName}} /webroot/
CMD /webroot/{{.buildName}} -config=/webroot/ {{.taskName}}
